spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:octoevents
    username: sa
    password: password
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        connection:
          provider_disables_autocommit: false
        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
server:
  error:
    include-stacktrace: never
  compression:
    enabled: true